name: Daily Cron Job at 12:00UTC

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma
        run: npx prisma generate

      - name: Run js script
        run: npm run script
