name: Daily Cron Job at 7:35UTC

on:
  schedule:
    - cron: "35 7 * * *"

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run js script
        run: npm run script
